url: http://kirbyt.github.io
baseurl: /timeline-jekyll-theme

# Site Settings
title: Timeline
description: "If you want to know a little bit more about me, see below"
keywords: "jekyll, theme"
google-tracking-id:

# Career Settings
# Default career thumbnail image.
career-img: "img/timeline/milla.jpg"

exclude: ["Rakefile", "LICENSE", "readme.markdown"]
